### ISSUE TITLE
Does gitlab have to be installed in system to use GITLAB_HOST ?

### ISSUE THREAD

**Issue by aidiss** [jupyterhub/oauthenticator#120]
I created system variable with GITLAB_HOST="http://[ip]"
and $GITLAB_HOST show its ok.
But when I try to login I get redirected to gitlab.com instead of custom server.
Is there any log that shows jupyterhub trying to get the env variable?
Maybe I need gitlab installed on system? I found that GITLAB_HOST is variable used by gitlab.

**Comment by willingc** [comment]
Thanks for the question @aidiss.

@Analect Do you have a working GitLab deployment? If so, would you let us know if there are any particular configuration steps that need to be done for GitLab?

**Comment by Analect** [comment]
@aidiss 
Assuming your self-hosted gitlab is running at `http://[ip]`, as per your comment above, then that needs to get passed, as you mentioned as a `GITLAB_HOST` environment variable on the hub, so that it gets picked-up as an over-ride value for gitlab.com, as per [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/gitlab.py#L28).  It sounds like this may not be happening.

I'm assuming you have followed the readme in terms of specifying in the `jupyterhub_config.py` in your hub that you are using gitlab as the authenticator?  I presume so, if you are ending up getting pointed at `gitlab.com`.

How are you spawning the hub?  Are you using something like dockerspawner or kubespawner (as per zero-to-jupyterhub).  If the latter, then your GITLAB_HOST is most easily passed to the jupyterhub pod via the `config.yaml` file as follows:

```
hub:
    extraEnv:
        GITLAB_HOST: "http://[ip]"
```
If you are using docker to run-up a hub, then you may have to pass `-e GITLAB_HOST="http://[ip]` as part of the docker run script, in order to pass the the env variable to the hub.

If this doesn't get you any further, come back here with more info ref your set-up and I can see if I can help further.

**Comment by aidiss** [comment]
@Analect 
yes, I followed the tutorial.
I am running jupyterhub with `jupyterhub --ip 0.0.0.0`

I did run `GITLAB_HOST="http://[giltlab_host_ip]"` and 
`echo $GITLAB_HOST` return  https://[gitlab_host_ip]


I did create an application on our custom gitlab and I did copy settings to my account and I did copy the values 


```
#jupyterhub_config.py
from oauthenticator.gitlab import GitLabOAuthenticator
c.JupyterHub.authenticator_class = GitLabOAuthenticator

c.MyOAuthenticator.oauth_callback_url = 'http://[jupyter_hub_host_ip]:8000/oauth/oauth_callback'
c.MyOAuthenticator.client_id = '..'
c.MyOAuthenticator.client_secret = '..'
```

**Comment by Analect** [comment]
@aidiss  ... sorry ... it's not obvious to me what the problem is.

For what it's worth, my method of starting the hub, which is dockerized, is:
`CMD jupyterhub --config /srv/jupyterhub_config.py --no-ssl --debug` ... you may want to try that, to at least get more debugging info  ... and then just have `c.JupyterHub.hub_ip = '0.0.0.0'` within the jupyterhub_config.py file.

I'm not sure what version of the hub you are installing ... 0.7.2 ... or the newer pre-release `0.8.x` version?  If it's a case you are using the latter, then I think you need to add `c.ConfigurableHTTPProxy.should_start = False` to the config file tool if it's a case that you are using an external proxy ... ie. you are telling jupyterhub not to use the internal proxy.

**Comment by jkinkead** [comment]
Did you export `GITLAB_HOST` to ensure that jupyterhub sees it?

I have this working fine with an internal GitLab repository.

**Comment by ghezalsherdil** [comment]
@jkinkead I have GITLAB_HOST set as the environment variable, however I am still getting redirected to gitlab.com. I also tried setting os.environ['GITLAB_HOST'] = '<local gitlab host>' in my jupyterhub_config.py config file, but no luck. Have you have done anything different then what is in the README.md?

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Comment by Economax** [comment]
If using JupyterHub Kubernetes with a config file: You implement GitLab Oauth under the hub tag.

It is important that you set GITLAB_HOST or GITLAB_URL under extraEnv _before_ implementing config.

Do not try to set gitlab_url under config, as that fails in version 1.2 of the Helm chart, corresponding to JupyterHub version 1.5.0.

Example:
```
hub:
  extraEnv: #VERY IMPORTANT THAT THIS COMES BEFORE CONFIG
      GITLAB_HOST: <https://gitlab.your-domain.com>
      GITLAB_URL: <https://gitlab.your-domain.com> #Redundancy
  config:
    GitLabOAuthenticator:
      #Client_id and client_secret under active-aml here: <https://gitlab.your-domain.com/admin/applications>
      client_id: <GitLab Application ID>
      client_secret: <GitLab Secret>
      oauth_callback_url: <https://gitlab.your-domain.com/hub/oauth_callback>
    JupyterHub:
      authenticator_class: gitlab
```

@consideRatio should this be added to docs at [https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html)? There is currently sparse documentation on how to implement the GITLAB_HOST flag, and it was not obvious that the environment variable had to be set before the config!

**Comment by consideRatio** [comment]
@Economax I think the z2jh must do its best to link out to this projects documentation - because it has proven to be unsustainable to keep it updated as this project changes.

With this said though, I think we won't need to specify any environment variables, and that everything should be configurable via `c.GitLabOAuthenticator` (or the eqvauilent in z2jh Helm chart config: `hub.config.GitLabOAuthenticator`).

From the following configuration, I note that what is relevant to configure, is `gitlab_url`.

https://github.com/jupyterhub/oauthenticator/blob/3bcb7a7293ba99bae16eddb37e3177082a54234c/oauthenticator/gitlab.py#L44-L73

Example Helm chart configuration:

```yaml
hub:
  config:
    GitLabOAuthenticator:
      #Client_id and client_secret under active-aml here: <https://gitlab.your-domain.com/admin/applications>
      client_id: <GitLab Application ID>
      client_secret: <GitLab Secret>
      oauth_callback_url: <https://gitlab.your-domain.com/hub/oauth_callback>
      gitlab_url: <https://gitlab.your-domain.com>
    JupyterHub:
      authenticator_class: gitlab
```

Also, note that the comment `extraEnv: #VERY IMPORTANT THAT THIS COMES BEFORE CONFIG` is irrelevant. The ordering of keys what you have in the helm chart YAML values won't matter.

---

I see that you mention version 1.2.0 of the Helm chart, corresponding to JupyterHub 1.5.0 etc - that seems irrelevant - right? What could be relevant would be the version of the `oauthenticator` package is installed in the 1.2.0 helm chart. Which is... `14.2.0` as seen via https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1.2.0/images/hub/requirements.txt#L95-L96.

Looking at the code from 14.2.0 in oauthenticator, I don't see any change to the relevant configuration section: https://github.com/jupyterhub/oauthenticator/blob/14.2.0/oauthenticator/gitlab.py#L44-L73.

My conclusion. GITLAB_HOST / GITLAB_URL should not be referenced, only `gitlab_url`.

Z2JH doesn't have an example for GitLab in its documentation yet, but I don't think we should maintain more examples there - for sustainability of maintenance of z2jh - we can't duplicate documentation in the extent we have had in the past.
