### ISSUE TITLE
AzureAdOAuthenticator: got 400 bad request during authentication

### ISSUE THREAD

**Issue by iVincentFeng** [jupyterhub/oauthenticator#218]
I set up a JupyterHub on a Kubernetes cluster on Azure, following [Zero to JupyterHub with Kubernetes](https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html).
I'd like to use AzureAdOAuthenticator for user authentication with following configuration.
```
proxy:
  secretToken: <secret_token>
hub:
  extraEnv:
    AAD_TENANT_ID: <tenant>
    OAUTH2_TOKEN_URL: https://login.microsoftonline.com/<tenant>/oauth2/token
    OAUTH2_AUTHORIZE_URL: https://login.microsoftonline.com/<tenant>/oauth2/authorize
  extraConfig: |
    c.JupyterHub.log_level = "DEBUG"
auth:
  type: custom
  custom:
    className: oauthenticator.azuread.AzureAdOAuthenticator
    config:
      client_id: <client_id>
      client_secret: <client_secret>
      oauth_callback_url: http://<jupyterhub_proxy_ip>/hub/oauth_callback
      token_url: https://login.microsoftonline.com/<tenant>/oauth2/token
      authorize_url: https://login.microsoftonline.com/<tenant>/oauth2/authorize
```
But I got a 404 bad request error in the logs.
Am I missing something or is there anything I've done wrong? Please help and provide suggestions. Thanks a lot in advance!
```
[E 2018-09-30 03:29:41.797 JupyterHub web:1670] Uncaught exception GET /hub/oauth_callback?code=AQABAAIAAADXzZ3ifr-GRbDT45zNSEFERd7e5C6fKyFXn5J1TG62W2kj5z9J0yaNtY9p9qbxsqhxKtXjI7jKho5stVKDosJxoIAJf_eSwOxVZKlvF9r_-MrS0b3O0oLwVYBoa9jm8_ZSzp2pIRVHcKld4HB_iQDd8AoiZh5dCxgAXEiS-l_hH6bqiqYbDCYofKcggHQzsBRCAAHDU1CadLjE_G3NLZE0pOhgvELM10_Uv7AGdDkW-h8KUjTpsnl7fHfoPL9KjpedNgHen5eAMBgv9EDMj9euClSxJ2yAVe56CXgWfRCe8B-g_mP0f3Z9fcfY9vBWi5kYKCJPvgnVhuwOjiEdP4WptiWm1_Wu9b7E61cPZw0jLSgJUfxPFPSHooZzAKBVQW-R2XXzdeGmMRqZgEZtph5A4r8jMxQfqdTYf8mFJ7F0cjt9B2ynn5fmiS9L6EbwzRQacFB6CSuMZCqqdVvypOqcbKsThQzPrKzAreMwZNuakLOE-Aq56DUqvWXX74GZ0vNutSfqqD-Byq07MUvoSFMvJs7kJ8FrccP17-J6zT0I7_An6xWuV9GsuWoWKSD5HWjPIIyJ1_l2HG8Zhk5vNHW1fw5XksrDfUxiLCoK-FEWM0kSvcHsOhj9WeJMuLLx866o4lN_MU6BZGaD7iqHx5dkFjyK6tR3eIxpYjw6JihFP055nhfWe7sb3B_ASgyLE64gAA&state=eyJzdGF0ZV9pZCI6ICI4Njg3MTZhMjg0ZDQ0MTVmYjI0OWQ1MDg1MDFiOTRmNSIsICJuZXh0X3VybCI6ICIifQ%3d%3d&session_state=35354cd5-9565-4628-a035-34154e9eaeba (<remote_ip>)
    HTTPServerRequest(protocol='http', host='<jupyterhub_proxy_ip>', method='GET', uri='/hub/oauth_callback?code=AQABAAIAAADXzZ3ifr-GRbDT45zNSEFERd7e5C6fKyFXn5J1TG62W2kj5z9J0yaNtY9p9qbxsqhxKtXjI7jKho5stVKDosJxoIAJf_eSwOxVZKlvF9r_-MrS0b3O0oLwVYBoa9jm8_ZSzp2pIRVHcKld4HB_iQDd8AoiZh5dCxgAXEiS-l_hH6bqiqYbDCYofKcggHQzsBRCAAHDU1CadLjE_G3NLZE0pOhgvELM10_Uv7AGdDkW-h8KUjTpsnl7fHfoPL9KjpedNgHen5eAMBgv9EDMj9euClSxJ2yAVe56CXgWfRCe8B-g_mP0f3Z9fcfY9vBWi5kYKCJPvgnVhuwOjiEdP4WptiWm1_Wu9b7E61cPZw0jLSgJUfxPFPSHooZzAKBVQW-R2XXzdeGmMRqZgEZtph5A4r8jMxQfqdTYf8mFJ7F0cjt9B2ynn5fmiS9L6EbwzRQacFB6CSuMZCqqdVvypOqcbKsThQzPrKzAreMwZNuakLOE-Aq56DUqvWXX74GZ0vNutSfqqD-Byq07MUvoSFMvJs7kJ8FrccP17-J6zT0I7_An6xWuV9GsuWoWKSD5HWjPIIyJ1_l2HG8Zhk5vNHW1fw5XksrDfUxiLCoK-FEWM0kSvcHsOhj9WeJMuLLx866o4lN_MU6BZGaD7iqHx5dkFjyK6tR3eIxpYjw6JihFP055nhfWe7sb3B_ASgyLE64gAA&state=eyJzdGF0ZV9pZCI6ICI4Njg3MTZhMjg0ZDQ0MTVmYjI0OWQ1MDg1MDFiOTRmNSIsICJuZXh0X3VybCI6ICIifQ%3d%3d&session_state=35354cd5-9565-4628-a035-34154e9eaeba', version='HTTP/1.1', remote_ip='<remote_ip>')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/azuread.py", line 96, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 400: Bad Request

[D 2018-09-30 03:29:41.800 JupyterHub base:880] No template for 500
[E 2018-09-30 03:29:41.810 JupyterHub log:150] {
      "X-Forwarded-Host": "<jupyterhub_proxy_ip>",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "<remote_ip>",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Cookie": "__lnkrntdmcvrd=-1; _xsrf=2|65fd80af|81849a5074f8c859bd61e2d6233c3d19|1538211402; oauthenticator-state=\"2|1:0|10:1538278179|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSTROamczTVRaaE1qZzBaRFEwTVRWbVlqSTBPV1ExTURnMU1ERmlPVFJtTlNJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|abbe47764315c0a08c53ccdab03f6da523cd7c63865dcf9c387e8fd8146a1741\"",
      "Referer": "http://<jupyterhub_proxy_ip>/hub/login",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0",
      "Host": "<jupyterhub_proxy_ip>"
    }
[E 2018-09-30 03:29:41.810 JupyterHub log:158] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@<remote_ip>) 47.08ms
```

**Comment by iVincentFeng** [comment]
After several retries, it is found out that both AAD_TENANT_ID and tenant_id need to be presented in config.yaml to make it work.
Missing AAD_TENANT_ID leads to incomplete authorization url, i.e., https://login.microsoftonline.com//oauth2/authorize.
Missing tenant_id gives the 400 bad request.
```
hub:
  extraEnv:
    AAD_TENANT_ID: "microsoft.onmicrosoft.com"
auth:
  type: custom
  custom:
    className: "oauthenticator.azuread.AzureAdOAuthenticator"
    config:
      tenant_id: "microsoft.onmicrosoft.com"
      client_id: "e825a33e-465c-430c-b73b-f404574cfd69"
      client_secret: "L//WF3Y7zZkLUwBabiPLywtV/Ly5vRUDhPj/jw7foXw="
      oauth_callback_url: "http://40.113.232.163/hub/oauth_callback"
```
