### ISSUE TITLE
 Callback problem with openid

### ISSUE THREAD

**Issue by kangzebin** [jupyterhub/oauthenticator#229]
Hi,

I set up jupyterhub in Kubenetes correctly but when I enable openid with the configuration below, I keep getting the error like 
```
400 GET /hub/oauth_callback?error=invalid_scope&error_description=CWOAU0065E%3A+The+authorization+server+cannot+process+the+%5BOpenID%2BConnect%2Brequest%5D+request.+It+is+missing+the+required+scope+parameter.&state=eyJzdGF0ZV9pZCI6ICI0YmYxMjY1ZTA1ZDE0YmM2YWY1OTFlOGMyMjA1MmNmYiIsICJuZXh0X3VybCI6ICIifQ%3D%3D (10.141.33.81): OAuth callback made without a code
```

My config.yaml for auth is:
```
hub:
  extraEnv:
    OAUTH2_AUTHORIZE_URL: https://w3id.alpha.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/authorize
    OAUTH2_TOKEN_URL: https://w3id.alpha.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/token
#    OAUTH_CALLBACK_URL: https://stagingglobal.com/hub/oauth_callback
    OAUTH_CLIENT_ID: ZDFkYTY2N2ItMmUzMi00
    OAUTH_CLIENT_SECRET: secret 
auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    clientId: "ZDFkYTY2N2ItMmUzMi00"
    clientSecret: "secret"
    token_url:  https://w3id.alpha.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/token
```
