### ISSUE TITLE
Does oauthenticator work with Amazon Cognito?

### ISSUE THREAD

**Issue by Jeffwan** [jupyterhub/oauthenticator#248]
/question.

Does JupyterHub OAuthenticator work with [Amazon Cognito](https://us-west-2.console.aws.amazon.com/cognito/home?region=us-west-2) User Pool?

**Comment by cristiklein** [comment]
Yes.

I configured the Cognito UserPool as follows:
- General settings -> App clients: The client needs a secret (note down the client ID and client secret)
- App integration -> App client settings: Make sure you have the correct callback URL configured (https://YOUR_DOMAIN/hub/oauth_callback)
- App integration -> Domain name: Add a friendly domain to your Cognito UserPool

Here is how I configured JupyterHub via the Helm Chart:

```
 hub:
    extraEnv:
      OAUTH_CALLBACK_URL: https://YOUR_DOMAIN/hub/oauth_callback
      OAUTH2_AUTHORIZE_URL: https://COGNITO_CUSTOM_DOMAIN/oauth2/authorize
      OAUTH2_TOKEN_URL: https://COGNITO_CUSTOM_DOMAIN/oauth2/token
      OAUTH2_USERDATA_URL: https://COGNITO_CUSTOM_DOMAIN/oauth2/userInfo
  auth:
    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "AWS Cognito"
        client_id: COGNITO_CLIENT_ID
        client_secret: COGNITO_CLIENT_SECRET
```
