### ISSUE TITLE
BUG?: TLJH OAuth redirecting to "GitLab.Com" URL rather than my own "GitLab-CE" URL as instructed ...

### ISSUE THREAD

**Issue by nmvega** [jupyterhub/oauthenticator#348]
Hello Friends:

_This is a restatement of my issue_ [here](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/548), _which when I opened it, didn't know whether to post it_ [_there_](https://github.com/jupyterhub/the-littlest-jupyterhub/issues/548) _or here. My apologies for the cross-post. I will update them both, as solutions come along._

**My issue**:
I have `GitLab CE` installed and use it as the `Oauth` authentication mechanism for my various `JupyterHub` builds: `SystemdSpawner`, `DockerSpawner`, etc. It works well.

However, for my new `TLJH` installation, when I click on `Sign in with GitLab`, the redirect takes me to the `GitLab.com` URL rather than my own `GitLab CE` URL. 

I've tried numerous things, including creating the file `/opt/tljh/config/jupyterhub_config.d/customize.py`, and trying combinations of the following within it and `reload`ing (but with no luck):
```
import os
# 
GITLAB_HOST = 'https://gitlab.k8sbox.io:443'  # Including w/o 'https://'.
GITLAB_URL = 'https://gitlab.k8sbox.io:443'
#
os.environ['GITLAB_HOST'] = GITLAB_HOST
os.environ['GITLAB_URL'] = GITLAB_URL
#
```
I'm using the latest version of `TLJH` (downloaded and installed today).

I pasted my redacted `config.yaml` file below.
Any ideas and help? I'm out of ideas. Thank you in advance!

```
users:
  admin:
  - jdoe
https:
  enabled: true
  port: 8443
  letsencrypt:
    email: jdoe@example.com
    domains:
    - jupyterhub.k8sbox.io
  tls:
    key: /etc/jupyter.d/conf.d/ssl.d/jupyterhub.key
    cert: /etc/jupyter.d/conf.d/ssl.d/jupyterhub.crt
http:
  port: 80
limits:
  memory: 4G
  cpu: 12
user_environment:
  default_app: jupyterlab
auth:
  GitLabOAuthenticator:
    client_id: XXXXXXXXXXXXXXXXXXXXXXXXXX
    client_secret: YYYYYYYYYYYYYYYYYYYYYYYYYY
    oauth_callback_url: https://jupyterhub.k8sbox.io:8443/hub/oauth_callback
    server_address: https://gitlab.k8sbox.io:443
  type: oauthenticator.gitlab.GitLabOAuthenticator
```
