### ISSUE TITLE
Gitlab OAuthenticator not honoring the whitelist

### ISSUE THREAD

**Issue by TiemenSch** [jupyterhub/oauthenticator#387]
### Bug description

The user whitelist is not being honored when using the Gitlab OAuthenticator. I've got JupyterHub set up using the zero-to-jupyterhub guide. See also https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1914

Currently, random users are spawning in my server, hence the dupe here as it's kind of urgent!

#### Expected behaviour

Only users in the whitelist should be able to login to the JupyterHub.

#### Actual behaviour

Any Gitlab user is able to login and use the JupyterHub instance.

### How to reproduce

Try logging in with a Gitlab account not in the whitelist.

### Your personal set up

```yaml
auth:
  whitelist:
    users:
      - user1
      - user2
  admin:
    access: true
    users:
      - <REDACTED>
  type: gitlab
  gitlab:
    clientId: <REDACTED>
    clientSecret: <REDACTED>
    callbackUrl: <REDACTED>
  scopes:
    - "read_user"
```
 - OS: Linux
 - Version: Chart 0.10.2
 - Configuration: See above.
