### ISSUE TITLE
[GitHub] OAuth fails with second computer attempting to log in

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/oauthenticator#417]
### Bug description

When I log into JupyterHub with GH OAuth on one machine and then try and log in on a different machine with the same user I get a 500.

#### Expected behaviour

I would expect to be able to log in
#### Actual behaviour

Error 500
### Your personal set up
zero-tojupyter-hub, with oauthenticator==0.13.0

- <details><summary>Logs</summary>
```
LyJ9 (10.42.0.112)
    HTTPServerRequest(protocol='http', host='holdenkarau.mooo.com', method='GET', uri='/hub/oauth_callback?code=[CODE]&state=[STATE]', version='HTTP/1.1', remote_ip='10.42.0.112')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 224, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 749, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 462, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/github.py", line 171, in authenticate
        resp = await http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
    
[E 2021-03-17 19:37:44.650 JupyterHub log:173] {
      "X-Real-Ip": "10.42.0.112",
      "X-Forwarded-Server": "traefik-758cd5fc85-dx5zk",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "holdenkarau.mooo.com",
      "X-Forwarded-For": "10.42.0.112,::ffff:10.42.0.113",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "cross-site",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Referer": "https://holdenkarau.mooo.com/",
      "Cookie": "_xsrf=[secret]; oauthenticator-state=[secret]",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
      "Host": "holdenkarau.mooo.com",
      "Connection": "close"
    }
[E 2021-03-17 19:37:44.650 JupyterHub log:181] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@10.42.0.112) 469.79ms

```
</details>

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by holdenk** [comment]
I'll give it a shot. So far I get "Sorry, there was an error authorizing your account. Please try again." when I try and use discourse (both GH and e-mail account creation).

I would have thought if it was a configuration issue it just wouldn't work at all instead of working for the first OAuth login?

**Comment by consideRatio** [comment]
Btw the user I found in the discourse forum was not associated with a GitHub account, so presumably it was an account registered via email. If you had trouble there as well using GitHub, I wonder if you may have some issues with your GitHub account somehow, or that you are signed into an account that you didn't expect on github.com etc?

**Comment by holdenk** [comment]
Makes sense. I'll do this in an incognito window tomorrow to verify :) Otherwise I'll see if maybe there's a cookie to clean I could add to the error message or similar.

**Comment by holdenk** [comment]
I tried it again today in an incognito window and I still get an error 500 on the second computer that I attempt to log in from. It's not a blocker for me (I'll just switch auth mechanisms), but if other folks run into this and want to collaborate into figuring out what's going on I'd love to :)

**Comment by consideRatio** [comment]
@holdenk btw, I got an idea of what may be wrong.

Are you always using HTTPS when you configure how to work against GitHub? I think that may be required. I suspect that GitHub responds with 403 forbidden because oauthenticator sends out a HTTP rather than HTTPS request when it only accepts HTTPS for these stuff.

**Comment by holdenk** [comment]
That could make sense. I was looking at the configuration parameters and I could only see a way to force it to HTTP (which I don't want), I'll take another look this weekend and see (and I'll share my config tomorrow - the secrets).

**Comment by holdenk** [comment]
```
hub:
  image:
    name: holdenk/jupyter-hub-magichub
# GitHub OAuth doesn't work well with multiple computers and same account :/
  config:
    GitHubOAuthenticator:
      client_id: ID
      client_secret: SECRET
      oauth_callback_url: "https://holdenkarau.mooo.com/hub/oauth_callback"
      allowed_organizations:
        - scalingpythonml
      scope:
        - read:user
    Authenticator:
      admin_users:
        - holdenk
      enable_auth_state: true
    CryptKeeper:
      keys:
        - SECRET
    DummyAuthenticator:
      password: FALLBACKPASSWORD
    JupyterHub:
      authenticator_class: github
```

**Comment by consideRatio** [comment]
Thanks @holdenk!

The next step for this issue would be to verify this bug doesn't have to do with the following configuration options.
- [ ] using a custom hub image
- [ ] using allowed_organizations

```
hub:
  config:
    GitHubOAuthenticator:
      client_id: ID
      client_secret: SECRET
      oauth_callback_url: "https://holdenkarau.mooo.com/hub/oauth_callback"
      scope:
        - read:user
    Authenticator:
      admin_users:
        - holdenk
    JupyterHub:
      authenticator_class: github
```

**Comment by holdenk** [comment]
So I need the custom image because I'm running on ARM. But I can try and deploy on MiniKube I suppose.

**Comment by consideRatio** [comment]
@holdenk oh cool okay sounds relatively harmless, perhaps that is something we can publish as part of the Helm chart as well btw?

How do you go about building the image? Are you simply doing `docker build` from an ARM linux environment?

**Comment by holdenk** [comment]
I'm using `docker buildx` with two backends configured (one x86 and one ARM machine). I did a write up on it at https://scalingpythonml.com/2020/12/12/deploying-jupyter-lab-notebook-for-dask-on-arm-on-k8s.html and I'll try and see about making a PR with the changes :)

**Comment by holdenk** [comment]
Ok I tried it again with:

```
hub:
# GitHub OAuth doesn't work well with multiple computers and same account :/
  config:
    GitHubOAuthenticator:
      client_id: ID
      client_secret: SECRET
      oauth_callback_url: "https://holdenkarau.mooo.com/hub/oauth_callback"
#      allowed_organizations:
#        - scalingpythonml
      scope:
        - read:user
    Authenticator:
      admin_users:
        - holdenk
      enable_auth_state: true
    CryptKeeper:
      keys:
        - KEY
    DummyAuthenticator:
      password: OTHERBACKUP
#    JupyterHub:
#      authenticator_class: dummy
    JupyterHub:
      authenticator_class: github
```
