### ISSUE TITLE
Problems with GitLabOAuthenticator

### ISSUE THREAD

**Issue by kianaf** [jupyterhub/oauthenticator#429]
Hi all, 

Sorry I am struggling with this problem from a long time ago. I am implementing the Zero to Jupyterhub on our Kubernetes cluster. As the Authenticator, I like to use the GitLab OAuthenticator but the problem is that even though I set the values in my config file like this:
```

hub:
  config:
    GitLabOAuthenticator:
      client_id: *
      client_secret: *
      oauth_callback_url: *
      scope:
        - api
        - read_repository
        - write_repository
    Authenticator:
      #gitlab_group_whitelist: ['*']
      #allowed_gitlab_groups: ['*']
      admin_users: ['*']
    JupyterHub:
      authenticator_class: oauthenticator.gitlab.GitLabOAuthenticator
 
```
I do not see the admin interface when I login with admin user. I should add our GitLab instance uses standard and ldap authentication. 

I also noticed that when I add allowed_gitlab_groups, I cannot authenticate at all getting this error in my hub pod logs: 

`tornado.curl_httpclient.CurlError: HTTP 599: SSL certificate problem: unable to get local issuer certificate`

Can anybody help me with that? It seems that it is being set BUT the values are not recognized. Then, in case of setting group you cannot login at all and in case of setting admin the mentioned user cannot see the admin panel. 

I would be grateful for any help on this.
