### ISSUE TITLE
GenericOAuthenticator doesnt redirect to the Identity server

### ISSUE THREAD

**Issue by malichishti** [jupyterhub/oauthenticator#452]
Hi,
I have set up Jupyter Hub on Ubuntu 20.x
I have then used tljh-config to set up identity provider as below:

```
abc@def:~$ sudo tljh-config show
users:
  admin:
  - admin
user_environment:
  default_app: jupyterlab
https:
  enabled: true
  letsencrypt:
    email: ma@def.com
    domains:
    - xx.southeastasia.cloudapp.azure.com
auth:
  GenericOAuthenticator:
    client_id: f120eeee-b3c2-477c-9dd8-725879a5bbd7
    client_secret: xyz
    token_url: https://yy.azurewebsites.net/identity/connect/token
    userdata_url: https://yy.azurewebsites.net/identity/connect/userinfo
    username_key: preferred_username
    login_service: yy
    oauth_callback_url: https://xx.southeastasia.cloudapp.azure.com/hub/oauth_callback
  OAuthenticator:
    client_id: f120eeee-b3c2-477c-9dd8-725879a5bbd7
    client_secret: xyz
  type: oauthenticator.generic.GenericOAuthenticator
os:
  environ[OAUTH2_TOKEN_URL]: https://yy.azurewebsites.net/identity/connect/token
  environ[OAUTH2_USERDATA_URL]: https://yy.azurewebsites.net/identity/connect/userinfo
  environ[OAUTH2_AUTHORIZE_URL]: https://yy.azurewebsites.net/identity/connect/authorize
```

However, when I try to log in, it gives the following error before even redirecting to my Identity provider:

https://xx.southeastasia.cloudapp.azure.com/hub/oauth_login?response_type=code&redirect_uri=https%3A%2F%xx.southeastasia.cloudapp.azure.com%2Fhub%2Foauth_callback&client_id=f120eeee-b3c2-477c-9dd8-725879a5bbd7&state=eyJzdGF0ZV9pZCI6ICJjYjM5ZjRlNjgzODU0ZDgyOWY0MjVmZDFiN2YwMTBmNyIsICJuZXh0X3VybCI6IG51bGx9
![image](https://user-images.githubusercontent.com/17155996/129871773-44af65ef-f2e5-463d-aa99-a34fac07893c.png)

Is there something i have done wrong?
