### ISSUE TITLE
Bitbucket Oauthenticator fails getting teams data

### ISSUE THREAD

**Issue by Marcalberga** [jupyterhub/oauthenticator#476]
### Bug description

BitbucketOauthenticator is using a [removed endpoint](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get) for checking user membership in authorized teams, should use [workspaces endpoint](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-get) instead.

#### Expected behaviour

Normal behaviour is expected, user can log in into jupyter if part of workspace

#### Actual behaviour

500 Error thrown.

### How to reproduce

Login with bitbucket with <1.2.0 version (not tested in 1.2.0)

### Your personal set up
zero-to-jupyterhub helm chart on EKS (AWS)

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```yaml
# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

hub:
  config:
    JupyterHub:
      admin_access: true
      admin_users: 
        - an_admin_user
      authenticator_class: "oauthenticator.bitbucket.BitbucketOAuthenticator" 
      BitbucketOAuthenticator:
        oauth_callback_url: "http://url_callback_working_just_fine"
        client_id: this_is_not_shareable
        client_secret: so_secret_change_it
        allowed_teams: 
          - "my_super_team"
  baseUrl: "/"
  image:
    name: jupyterhub/k8s-hub
    tag: "1.1.4"
    pullPolicy:
    pullSecrets: [] 
singleuser:
  defaultUrl: "/lab"
  image: 
    name: jupyter/scipy-notebook
    tag: hub-1.4.1
  profileList:
    - display_name: "Python Environment"
      description: "Python default environment"
      default: true
    - display_name: "R Environment"
      description: "R basic environment"
      kubespawner_override:
        image: jupyter/r-notebook:latest
```
</details>

- <details><summary>Logs</summary>
```
[E 2022-01-07 08:08:56.696 JupyterHub oauth2:389] Error fetching 404 GET https://api.bitbucket.org/2.0/teams: {
     "error": {
      "message": "This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get"
     },
     "type": "error"
    }
```
</details>
