### ISSUE TITLE
A way to ban users

### ISSUE THREAD

**Issue by darabos** [jupyterhub/oauthenticator#481]
### Proposed change

Let's provide a mechanism for banning users. Something like:

```
hub:
  config:
    Authenticator:
      admin_users:
      - daniel.darabos@lynxanalytics.com
      banned_users:
      - hacker001@example.com
      - hacker002@example.com
```

### Alternative options

I'm currently manually deleting offending users, but nothing stops them from coming back 5 minutes later.

### Who would use this feature?

We run a JupyterHub instance to demo our data science product. A person is abusing this to mine cryptocurrency on as many demo instances as they can start. We require a Google account sign-in for using the demo. Hopefully the abuser would run out of Google accounts if we ban enough.

If you think this is a good idea, I'm happy to work on implementing it. (If OAuthenticator even is the right place to implement this. Sorry, I'm a bit lost. Thanks for any advice.)
