### ISSUE TITLE
google auth in oauthenticator 16.x changes username format

### ISSUE THREAD

**Issue by taylorgibson** [jupyterhub/oauthenticator#660]
### Bug description

When upgrading `jupyterhub` to helm chart `3.0.0-beta.3.git.6268.h16086582`, which contains version 16 of `oauthenticator`, usernames are parsed differently on log in when using google authenticator. Previously, only the portion of the email address before the domain name was used to identify and name a user, and now the full email address is used. For example, `taylorgibson` is now `taylorgibson@example.com`. Jupyterhub views these as two distinct users, and therefore a new account is created. Users are unable to access storage allocated to the old version of the username since it is viewed as a separate account. 

I can confirm that downgrading to a previous version (helm chart `3.0.0-alpha.1.git.6194.h835c3fa8`) reverts the behavior to what I would expect. The only changes in the `config.yaml` file between the two versions was the addition/removal of the `allow_all: true` required with version 16. You can see the relevant configuration portion below in this issue.

I have not tried upgrading to the latest helm charts released today (`3.0.0-beta.3.git.6273.hae30a841`) to see if the bug persists. 

#### Expected behaviour

When users log in using Google OAuth, only the username (portion before the @) portion of the Google account email adddress is be used as the Jupyterhub user name.

#### Actual behaviour

When users log in using Google OAuth, the entire Google account email address is used as the Jupyterhub user name.

### How to reproduce

1. Upgrade Jupyterhub with a helm chart version that uses oauthenticator 16.x (I used `3.0.0-beta.3.git.6268.h16086582`)
2. Log in using Google authenticator

### Your personal set up

 
 - Version(s): juypyterhub (helm chart: `beta.3.git.6268.h16086582`) on Google Cloud Platform
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```
hub:
  config:
    Authenticator:
      admin_users:
        - gibson
    GoogleOAuthenticator:
      client_id: <redacted>
      client_secret: <redacted>
      oauth_callback_url: https://datahub.ncssm.edu/hub/oauth_callback
      hosted_domain:
        - ncssm.edu
      allow_all: true
      admin_users:
        - gibson
      login_service: NCSSM Account
    JupyterHub:
      authenticator_class: google
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
